### ISSUE TITLE
uglify-es is no longer maintained

### ISSUE THREAD

**Issue by feross** [browserify/tinyify#12]
Just ran into a nasty bug where the minified code that `tinyify` outputted was broken. I looked into it and discovered that `uglify-es` (which `uglifyify` uses under the hood) is no longer maintained.

Either we should:

1. Switch to a fork that is maintained. There's a PR for that here: https://github.com/hughsk/uglifyify, or:

2. Switch to a transform that uses `babel-minify` which I've used in the past (it works great on ES6+).

But the current `uglify-es` is full of bugs and won't be getting any more updates... :(

**Comment by toddself** [comment]
I would love to get this https://github.com/hughsk/uglifyify/pull/86 merged in, being that we are already using terser in tinyify.

Does anyone know if @hughsk has other people who can merge PRs?

**Comment by goto-bus-stop** [comment]
according to npm @hughsk  and @yoshuawuyts can do releases, i pinged yosh in irc

**Comment by goto-bus-stop** [comment]
That pr was merged and published as uglifyify@5.0.1, doing `npm update` should fix your troubles! :sparkles:

**Comment by toddself** [comment]
huzzah.  Thanks @goto-bus-stop and @yoshuawuyts

**Comment by feross** [comment]
Wohoo! 🙌

**Comment by stevenvachon** [comment]
[terser](https://npmjs.com/terser) is the successor to uglify-es.

**Comment by toddself** [comment]
@stevenvachon  -- yes and uglifyify now uses that
