### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by niftylettuce** [browserify/tinyify#14]
See full debugging output at <https://github.com/visionmedia/superagent/issues/1418#issuecomment-424961250>.  Happens with `superagent` for some reason.

**Comment by niftylettuce** [comment]
Curious if someone saw anything immediately wrong come to mind?

**Comment by josephg** [comment]
Fixed - it was a bug in common-shakeify: browserify/common-shakeify#18, which @goto-bus-stop published as 📦 0.5.2

Tinyify is still pointing at ^0.4 - Can someone bump the version of shakeify in tinyify's package.json & republish?

**Comment by niftylettuce** [comment]
pinging @goto-bus-top

**Comment by niftylettuce** [comment]
Yes please bump and publish new version

ping @goto-bus-stop
