### ISSUE TITLE
Issues while browserifying peermaps-web

### ISSUE THREAD

**Issue by ralphtheninja** [browserify/tinyify#31]
Hi!

I have some issues in `peermaps-web` when I add `-p tinyify` to browserify. Trying to wrap my head around what the issue is and was hoping you could help me shed some light on what's going on.

```
> browserify
> browserify -p tinyify app.js | indexhtmlify --title 'peermaps' > public/index.html

Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/home/lms/src/peermaps/peermaps-web/worker_threads'
    required by /home/lms/src/peermaps/peermaps-web/node_modules/sodium-universal/memory.js
```

If I build `peermaps-web` without `tinyify` then there's no reference to `worker_threads` in the resulting `index.html`, so it could potentially be due to `tinyify` itself? In the dark here.

Cheers

**Comment by goto-bus-stop** [comment]
maybe browser-pack-flat tries to resolve a `worker_threads` reference that would otherwise be inside a dead `if`. you can try doing `-p [ tinyify --no-flat ]`

**Comment by ralphtheninja** [comment]
> maybe browser-pack-flat tries to resolve a `worker_threads` reference that would otherwise be inside a dead `if`. you can try doing `-p [ tinyify --no-flat ]`

Thanks for input. It produces the same error unfortunately.

**Comment by goto-bus-stop** [comment]
hmm, usually the flattening is at fault for any issues with tinyify, so that's a little unusual 😛  installing the tools separately and removing one at a time could pin down the culprit: https://github.com/browserify/tinyify#more-options

**Comment by ralphtheninja** [comment]
Found the culprit 

https://github.com/sodium-friends/sodium-javascript/blob/ae2df3305e0cff68c3ae922813bfbb2d361d78de/memory.js#L21

It tries to require `worker_threads` but the `package.json` has `worker_threads: false` which was added in https://github.com/sodium-friends/sodium-javascript/commit/f79aed4eee6524cd230a96cea45a11957b1151b6

**Comment by ralphtheninja** [comment]
I was wondering why this wasn't the issue before. Maybe it's because `tinyify` actually merges the strings together? I.e. `'worker' + '_threads'` becomes `'worker_threads'`?

**Comment by goto-bus-stop** [comment]
Yes tinyify has two minify steps: once the individual files and then also the whole output. The individual minification is mostly intended to remove conditional/unused requires before browserify includes them. But if the individual files are minified constant evaluation merges them together, and then browserify will see it as an actual functioning `require()` and try to resolve the module.

**Comment by goto-bus-stop** [comment]
I think `worker_threads: false` should make browserify resolve it to an empty module though, not crash entirely.

**Comment by ralphtheninja** [comment]
Yeah, it does crash though and if I comment out the require code it passes (get some other errors though but prob not related to this issue).

**Comment by ralphtheninja** [comment]
I can also confirm that if I replace `'worker' + '_threads'` with `'worker_threads'` and skip using `tinyify` altogether, then I have the same issue. So unrelated to what `tinyify` does.

**Comment by ralphtheninja** [comment]
Closing as unrelated to `tinyify`.
