### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by binarykitchen** [browserify/tinyify#8]
The other ticket confirmed ES2015 support is in, but still seeing the above error?

Isn't this a contradiction or do I have to transform code with babelify beforehand?

**Comment by goto-bus-stop** [comment]
ES modules don't work with browserify (yet?). ref eg https://github.com/browserify/browserify/issues/1186. All other new syntax does work.

> Isn't this a contradiction or do I have to transform code with babelify beforehand?

Yep, you need to transform ES modules still—perhaps using babelify, or a faster option might be [ascjsify](https://github.com/goto-bus-stop/ascjsify) which _only_ deals with ES modules.

**Comment by binarykitchen** [comment]
ah great thanks for pointing to ascjsify ...

... on a side note, would you be willing to add ascjsify to tinify's pipe? just an idea

**Comment by goto-bus-stop** [comment]
i think transpiling ES2015+ code is best done with another tool—the es2015+ support in tinyify only means that it can parse it: it doesn't transpile, so if you give it ES2015, it also outputs ES2015

**Comment by binarykitchen** [comment]
gotcha - fair enuff

**Comment by bfred-it** [comment]
Since this appeared pretty high in my google search, I'll offer a solution for other stumblers: https://github.com/mattdesl/esmify

```sh
browserify index.js -p esmify > bundle.js
```
