### ISSUE TITLE
Include bundle-collapser

### ISSUE THREAD

**Issue by binarykitchen** [browserify/tinyify#9]
If this package aims to aggressively reduce the file size, why not include https://github.com/substack/bundle-collapser as well?

**Comment by goto-bus-stop** [comment]
Tinyify uses browser-pack-flat which doesn't output file names in the first place, so replacing them with bundle IDs has no effect.

We could add it if the --no-flat flag is used tho!

**Comment by goto-bus-stop** [comment]
📦 2.4.0

**Comment by binarykitchen** [comment]
nice, that went fast
